# Generated by Django 5.1 on 2024-09-11 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('method', models.CharField(choices=[('online', '1V1'), ('offline', '班级')], max_length=10, verbose_name='授课方式')),
                ('teacher', models.CharField(max_length=100, verbose_name='教师')),
                ('class_name', models.CharField(max_length=100, verbose_name='班级')),
                ('student_count', models.IntegerField(verbose_name='学员人数')),
                ('fee_type', models.CharField(max_length=50, verbose_name='收费类型/课时')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('age', models.IntegerField(blank=True, verbose_name='年龄')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('enrollment_type', models.CharField(choices=[('hours', '课时'), ('days', '天数')], max_length=10, verbose_name='报课方式')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='家庭住址')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='学费')),
                ('parent_contact', models.CharField(blank=True, max_length=100, verbose_name='家长联系方式')),
                ('Admissionsteacher', models.CharField(blank=True, max_length=100, verbose_name='招生老师')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='课程')),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('head_name', models.CharField(max_length=10, verbose_name='部门负责人')),
                ('describe', models.CharField(blank=True, max_length=100, verbose_name='部门描述')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='部门地址')),
                ('number', models.CharField(blank=True, max_length=11, verbose_name='部门电话')),
            ],
        ),
        migrations.CreateModel(
            name='DaysInfo',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.student')),
                ('start_date', models.DateField(verbose_name='开始时间')),
                ('end_date', models.DateField(verbose_name='结束时间')),
            ],
        ),
        migrations.CreateModel(
            name='HoursInfo',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.student')),
                ('course_hours', models.IntegerField(verbose_name='课时长')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('hire_date', models.DateField(verbose_name='入职时间')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('status', models.CharField(choices=[('active', '在职'), ('inactive', '离职')], default='active', max_length=10, verbose_name='当前状态')),
                ('contact_info', models.CharField(blank=True, default='Unknown', max_length=100, verbose_name='联系方式')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department', verbose_name='所属部门')),
            ],
        ),
        migrations.CreateModel(
            name='FullCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('class_name', models.CharField(max_length=100)),
                ('work_type', models.CharField(choices=[('single', '自由排课'), ('repeated', '重复排课')], default='single', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
