# Generated by Django 5.1 on 2024-09-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullcalendar',
            name='color',
            field=models.CharField(default='blue', max_length=20),
        ),
    ]
