# Generated by Django 5.1 on 2024-09-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fullcalendar_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(verbose_name='支出日期')),
                ('reason', models.CharField(max_length=255, verbose_name='支出原因')),
                ('category', models.CharField(max_length=255, verbose_name='支出类别')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('payment_method', models.CharField(choices=[('WX', '微信'), ('ZFB', '支付宝'), ('CC', '信用卡'), ('BC', '银行卡'), ('GTT', '对公转账'), ('OTHER', '其他')], max_length=5, verbose_name='支付方式')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注信息')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateField(verbose_name='收入日期')),
                ('source', models.CharField(max_length=255, verbose_name='收入来源')),
                ('category', models.CharField(max_length=255, verbose_name='收入类别')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('payment_method', models.CharField(choices=[('WX', '微信'), ('ZFB', '支付宝'), ('CC', '信用卡'), ('BC', '银行卡'), ('OTHER', '其他')], max_length=5, verbose_name='支付方式')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注信息')),
            ],
        ),
    ]
