# Generated by Django 5.1 on 2024-09-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_expense_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(default='支出', max_length=10, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='income',
            name='type',
            field=models.CharField(default='收入', max_length=10, verbose_name='类别'),
        ),
    ]
