# Generated by Django 5.1 on 2024-09-24 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_expense_type_income_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('source_channel', models.CharField(max_length=100)),
                ('follow_up_status', models.CharField(choices=[('失效', '失效'), ('跟进中', '跟进中'), ('待跟进', '待跟进'), ('已签约', '已签约'), ('已邀约', '已邀约')], max_length=10)),
                ('last_follow_up_time', models.DateTimeField()),
                ('next_follow_up_time', models.DateTimeField()),
                ('enrollment_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('intended_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
    ]
