# Generated by Django 5.1 on 2024-09-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_teacher',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='intended_course',
            field=models.CharField(max_length=100),
        ),
    ]
