# Generated by Django 5.1 on 2024-09-27 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_enrollment_enrollment_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='source_channel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_notes', models.TextField()),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='app.enrollment')),
            ],
        ),
    ]
