# Generated by Django 5.1 on 2024-09-27 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_enrollment_source_channel_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
