# Generated by Django 5.1 on 2024-09-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_followup_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='follow_up_notes',
            field=models.CharField(max_length=120),
        ),
    ]
