# Generated by Django 5.1 on 2025-01-07 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'verbose_name': '活动日志', 'verbose_name_plural': '活动日志'},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='entity',
            field=models.CharField(choices=[('student', '学员'), ('income', '收入')], default='student', max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', '创建'), ('delete', '删除'), ('update', '更新'), ('retrieve', '查询')], max_length=10),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['timestamp'], name='app_activit_timesta_bc2648_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user'], name='app_activit_user_id_385657_idx'),
        ),
    ]
